---
title: 30th May 2025
---

# 30th May 2025

## Overview

On the 30th May 2025 when organising network elements physically in preparation of mounting into a network rack including the primary Proxmox Nodes a failure occurred resulting in neither node appearing to return back online and with only inbound traffic activity present.

Initial review showed what appeared to be both nodes powering on with inbound network indicators showing activity.

## Troubleshooting

Initial issues appeared to show the devices not actually booting up correctly or not connecting to the network

srv-lo-1 was connected to a monitor to observe the terminal during start-up where errors could be seen relating to the mounting of NFS file shares on a separate NAS, other than these errors the device appeared to boot as expected

```ip -a``` was run on the terminal which showed all interfaces as UP and in what appeared to be an operational state, vmbr0 a bridge adapter and the one assigned the static IPv4 address for the host itself however was only showing inet6 for IPv6 and not inet for IPv4

This made me wonder of the IPv4 config had been lost, having checked /etc/network/interfaces nothing appeared to be incorrect and the required configuration of the below was present:

| IP Address   | Default Gateway | Subnet Mask   |
| :----------: | :-------------: | :-----------: |
| 192.168.1.20 | 192.168.1.1     | 255.255.255.0 |

Performing a simple ping test to 8.8.8.8 also provided no luck cementing this did appear to be a network of sorts issue but in what appeared to be as a result of the bridge interface

Then I decided to toggle all the network interfaces down/up to see if this would bring the required interface alive and although it didn't fix the issue it can me the biggest clue with the below terminal output that was received when running ```ifdown -a```:

``` bat
warning: cannot load "address" module: cannot import name 'splat' from 'jaraco.functools' (/usr/lib/python3/dist-packages/jaraco/functools.py)
```

## Solution

After some research into this output it would appear to be a known issue, a suggestion of removing the referenced python package was one that had appeared to work for many, to ensure a rollback plan however I decided to rename the folder rather than remove and so issued the below command:

``` linuxconfig
mv /usr/lib/python3/dist-packages/jaraco /usr/lib/python3/dist-packages/jaraco-old
```

Attempting to toggle the interfaces this time did not appear to show any errors and the output of ```ip -a``` showed an inet address on the bridge adapter once again, attempting to connect via the webgui also worked successfully

A quick troubleshoot using the above steps on the other host srv-lo-2 also showed a similar story and as such the same fix was applied working immediately as well

## Permanent Fix

As this appears to have occurred on both hosts at the same time during essentially a reboot I can only assume that the package was updated prior and then caused issues during the start-up however this isn't confirmed and will need further investigation